[project]
name = "mandelbrot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.17.1",
    "numpy>=2.3.2",
    "pillow>=11.3.0",
]

[tool.mypy]
strict=true
ignore_missing_imports=true
